version: '3.1'

services:
  particle-homebridge-translation-api:
    image: dakl/particle-homebridge-translation-api:latest
    ports:
      - "8000:8000"
    secrets:
       - tv_backlight_device_id
       - relay_hub_device_id
       - particle_access_token
  homebridge:
    image: oznu/homebridge:raspberry-pi
    volumes:
      - ./homebridge/config.json:/homebridge/config.json:ro
      - ./homebridge/package.json:/homebridge/package.json:ro
    depends_on: 
      - particle-homebridge-translation-api
secrets:
  tv_backlight_device_id:
    external: true
  lego_house_device_id:
    external: true
  relay_hub_device_id:
    external: true
  particle_access_token:
    external: true
