version: '3.2'

services:

  particle-relay-hub-api:
    image: dakl/particle-relay-hub-api:latest
    ports:
      - "8001:8000"
    secrets:
       - relay_hub_device_id
       - lego_house_device_id
       - particle_access_token

  particle-relay-hub-handler:
    image: dakl/particle-relay-hub-handler:latest
    secrets:
       - relay_hub_device_id
       - lego_house_device_id
       - particle_access_token

  tv-backlight-api:
    image: dakl/tv-backlight-api:latest
    ports:
      - "8002:8000"
    secrets:
       - tv_backlight_device_id
       - particle_access_token

  mosquitto:
    image: dakl/rpi-mosquitto
    ports:
      - "1883:1883"

  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

secrets:
  tv_backlight_device_id:
    external: true
  lego_house_device_id:
    external: true
  relay_hub_device_id:
    external: true
  particle_access_token:
    external: true


networks:
  portainer_agent:
    driver: overlay
    attachable: true